window.AppConfig = {
  STORAGE_KEY: "citizen-tools-solo",
  DEFAULT_COLOR: "#163a63",
  PRESET_ORDER: {
    custom: -1,
    Origin: 0,
    MISC: 1,
    RSI: 2,
    Crusader: 3,
  },
  SHIP_MANUFACTURERS: [
    "Aegis",
    "Anvil",
    "ARGO",
    "CNOU",
    "Consolidated Outland",
    "Crusader",
    "Drake",
    "Esperia",
    "Gatac",
    "Greycat",
    "Kruger",
    "MISC",
    "Mirai",
    "Origin",
    "RSI",
    "Tumbril",
  ],
  APP_LANGUAGE_OPTIONS: [
    { value: "de", label: "Deutsch" },
    { value: "en", label: "English" },
  ],
  SHIP_CLASS_OPTIONS: [
    { value: "", labels: { de: "Keine Klasse", en: "No class" } },
    { value: "starter", labels: { de: "Starter", en: "Starter" } },
    { value: "exploration", labels: { de: "Erkundung", en: "Exploration" } },
    { value: "cargo", labels: { de: "Fracht", en: "Cargo" } },
    { value: "combat", labels: { de: "Kampf", en: "Combat" } },
    { value: "mining", labels: { de: "Bergbau", en: "Mining" } },
    { value: "salvage", labels: { de: "Bergung", en: "Salvage" } },
    { value: "racing", labels: { de: "Rennen", en: "Racing" } },
    { value: "specialized", labels: { de: "Spezialisiert", en: "Specialized" } },
    { value: "multi_role", labels: { de: "Mehrzweck", en: "Multi-Role" } },
    { value: "alien", labels: { de: "Alien", en: "Alien" } },
    { value: "refuel", labels: { de: "Betankung", en: "Refuel" } },
  ],
  REFUEL_SHIP_CLASSES: ["refuel"],
  LOCATION_SUGGESTIONS: [
    "Stanton",
    "Area18",
    "Baijini Point",
    "Everus Harbor",
    "Grim HEX",
    "Lorville",
    "New Babbage",
    "Orison",
    "Port Tressler",
    "Seraphim Station",
    "ARC-L1 Wide Forest Station",
    "ARC-L2 Lively Pathway Station",
    "ARC-L4 Faint Glen Station",
    "ARC-L5 Yellow Core Station",
    "CRU-L1 Ambitious Dream Station",
    "CRU-L4 Shallow Fields Station",
    "CRU-L5 Beautiful Glen Station",
    "HUR-L1 Green Glade Station",
    "HUR-L2 Faithful Dream Station",
    "HUR-L4 Melodic Fields Station",
    "HUR-L5 High Course Station",
    "MIC-L1 Shallow Frontier Station",
    "MIC-L2 Long Forest Station",
    "MIC-L4 Red Crossroads Station",
    "Pyro",
    "Pyro Gateway",
    "Ruin Station",
    "Pyro I",
    "Monox",
    "Bloom",
    "Pyro IV",
    "Pyro V",
    "Terminus",
    "Ignis",
    "Vuur",
    "Fuego",
    "Fairo",
    "Adir",
    "Vatra",
    "Nyx",
    "Levski",
    "Delamar",
    "Nyx I",
    "Nyx II",
    "Nyx III",
  ],
  FLEET_STATUS_LABELS: {
    active: "Aktiv",
    destroyed: "Zerstört",
    "patch-replaced": "Durch Patch ersetzt",
    "wipe-replaced": "Durch Wipe ersetzt",
    "wipe-removed": "Durch Wipe entfernt",
    sold: "Verkauft",
    melted: "Eingetauscht",
    inactive: "Nicht aktiv",
  },
  MISSION_TYPE_LABELS: {
    cargo: "Fracht",
    courier: "Kurier",
    delivery: "Lieferung",
    refuel: "Tanken",
    investigation: "Ermittlung",
    medical: "Medizin",
    service: "Service",
    salvage: "Salvage",
    procurement: "Beschaffung",
    mining: "Bergbau",
    combat: "Kampf",
    transport: "Transport",
    other: "Sonstiges",
  },
};
