"""Render the original Flight Deck synth cues as replaceable PCM WAV files."""
import json
import math
from pathlib import Path
import struct
import wave

ROOT = Path(__file__).resolve().parents[1]
PRESETS = {
    'tap': [[0, 740, 920, .045, 'sine']],
    'navigation': [[0, 1080, 1460, .045, 'sine'], [.052, 1540, 1380, .035, 'sine']],
    'confirm': [[0, 880, 1040, .055, 'sine'], [.085, 1320, 1760, .075, 'sine']],
    'dialog': [[0, 480, 720, .085, 'triangle'], [.055, 960, 1200, .06, 'sine']],
    'error': [[0, 280, 190, .09, 'triangle'], [.105, 190, 150, .06, 'sine']],
    'import-read': [[0, 640, 980, .06, 'sine'], [.08, 980, 1480, .07, 'sine']],
    'import-processing': [[0, 520, 640, .05, 'triangle'], [.12, 700, 820, .05, 'triangle'], [.24, 880, 1000, .06, 'triangle']],
    'import-success': [[0, 880, 1040, .06, 'sine'], [.08, 1320, 1480, .06, 'sine'], [.16, 1760, 1760, .12, 'sine']],
    'import-failure': [[0, 440, 280, .12, 'triangle'], [.16, 280, 170, .16, 'sine']],
}


def main():
    folder = ROOT / 'web/assets/sounds'
    folder.mkdir(parents=True, exist_ok=True)
    # The JS fallback and WAV renderer share one checked-in set of presets.
    (ROOT / 'web/scripts/sound-presets.js').write_text(
        '// Generated by tools/generate_sounds.py. Original Flight Deck cues.\n'
        + 'window.SoloSoundPresets = ' + json.dumps(PRESETS, indent=2) + ';\n', encoding='utf-8')
    rate = 44100
    for name, notes in PRESETS.items():
        samples = [0.] * math.ceil((max(n[0] + n[3] for n in notes) + .012) * rate)
        for offset, start_hz, end_hz, duration, shape in notes:
            phase = 0.
            for index in range(math.ceil(duration * rate)):
                t = index / rate
                phase += 2 * math.pi * start_hz * (end_hz / start_hz) ** (t / duration) / rate
                signal = math.sin(phase) if shape == 'sine' else 2 / math.pi * math.asin(math.sin(phase))
                envelope = t / .006 if t < .006 else (.0001 / .12) ** ((t - .006) / (duration - .006))
                samples[round(offset * rate) + index] += signal * .12 * envelope
        with wave.open(str(folder / f'{name}.wav'), 'wb') as output:
            output.setparams((1, 2, rate, 0, 'NONE', 'not compressed'))
            output.writeframes(b''.join(struct.pack('<h', round(max(-1, min(1, x)) * 32767)) for x in samples))
    print(f'{len(PRESETS)} original WAV cues generated.')


if __name__ == '__main__': main()
