// Exercise the real Solo app against an isolated SoloRuntime data directory.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, hasTouch:true });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(process.argv[2]);
    await page.waitForFunction(() => window.soloStartup?.phase === 'ready' && soloSync.status.hydrated && !soloSync.status.busy);
    await page.evaluate(() => {
      uiLanguageSelect.value = 'de';
      uiLanguageSelect.dispatchEvent(new Event('change'));
      state = sanitizeState({ ...state, levelFilter:'all', selectionCleared:false, autoload:{allowOverload:false},
        fleet: [{id:'camera-ship',shipId:'ship:hermes',manufacturer:'RSI',model:'Hermes',status:'active',acquiredOn:'2026-10-01'}],
        activeFleetEntryId:'camera-ship', missions:[{id:'camera-mission',type:'cargo',title:'Camera cargo',status:'active',
          assignedFleetEntryId:'camera-ship',pickup:'Area18',dropoff:'Lorville',payout:15000,
          segments:[{id:'camera-segment',title:'Titanium',pickup:'Area18',dropoff:'Lorville',width:1,depth:1,height:1,
            containerSize:'1',quantity:3,order:0,isPlaceable:true,scuPerLoad:1,totalScu:3}],
          loads:['a','b','c'].map(id => ({id,segmentId:'camera-segment',label:'Titanium '+id,width:1,depth:1,height:1,scu:1,pickup:'Area18',dropoff:'Lorville',placement:null}))}] });
      applyLayoutDefinition(getShipGridDefinition(findShipLibraryEntryById('ship:hermes')),'camera-ship','ship:hermes');
      setActivePage('load');
      state.selectedLoadId = 'a';
      render();
    });
    const check = async (expression, name, argument) => {
      assert(await page.evaluate(expression, argument), name);
      console.log('PASS', name);
    };
    const frameSize = () => page.locator('#loadIsoBody .cargo-camera-frame').evaluate(node => ({width:node.clientWidth,height:node.clientHeight}));
    const floor = () => page.locator('#isoView .iso-floor.placeable').first();
    await floor().hover();
    await check(() => !!isoView.querySelector('.cargo-placement-preview.is-valid') && !findLoadById('a').load.placement, 'valid hover previews without changing cargo');
    fs.mkdirSync('.build/container-view-check', {recursive:true});
    await page.locator('#loadIsoBody').screenshot({path:'.build/container-view-check/placement-preview.png'});
    await floor().hover();
    const preview = await page.locator('.cargo-placement-preview').evaluate(node => ({row:+node.dataset.row,col:+node.dataset.col,z:+node.dataset.z}));
    await floor().click();
    await check(expected => { const p=findLoadById('a').load.placement; return p.row===expected.row && p.col===expected.col && p.z===expected.z; }, 'click matches preview position', preview);
    await page.locator('#cargoUndoButton').click();
    await check(() => !findLoadById('a').load.placement && state.selectedLoadId==='a', 'undo button restores placement and selection');
    await page.evaluate(() => {findLoadById('a').load.height=100;render();});
    await page.locator('#isoView .iso-floor').first().hover();
    await check(() => !!isoView.querySelector('.cargo-placement-preview.is-invalid') && document.getElementById('cargoPlacementStatus').textContent.includes('Hier nicht möglich'), 'invalid hover shows red preview and reason');
    await page.keyboard.down('Control');
    await check(() => !isoView.querySelector('.cargo-placement-preview'), 'camera modifier hides placement preview');
    await page.keyboard.up('Control');
    await page.evaluate(() => {findLoadById('a').load.height=1;render();});
    await floor().click();
    const originalPlacement = await page.evaluate(() => structuredClone(findLoadById('a').load.placement));
    await page.evaluate(() => {state.selectedLoadId='a';handleCellClick(5,1);});
    await page.locator('#cargoUndoButton').click();
    await check(expected => JSON.stringify(findLoadById('a').load.placement)===JSON.stringify(expected), 'undo movement restores the exact former placement', originalPlacement);
    await page.evaluate(() => rotateLoad(findLoadById('a').load));
    await page.locator('#isoView').focus();
    await page.keyboard.press('Control+z');
    await check(() => !findLoadById('a').load.rotated && !!findLoadById('a').load.placement, 'Ctrl+Z undoes rotation');
    await page.keyboard.press('Control+z');
    await check(() => !findLoadById('a').load.placement, 'multiple undo restores earlier placement');
    await floor().click();
    await page.evaluate(() => unloadLoad(findLoadById('a').load));
    await page.locator('#cargoUndoButton').click();
    await check(() => !!findLoadById('a').load.placement, 'undo restores unloaded cargo');
    await page.locator('#cargoUndoButton').click();
    await page.evaluate(() => autoLoadMission(state.missions[0]));
    await check(() => state.missions[0].loads.every(load=>load.placement), 'autoload fills test cargo');
    await page.locator('#cargoUndoButton').click();
    await check(() => state.missions[0].loads.every(load=>!load.placement), 'one undo restores whole autoload action');
    await floor().click();
    await page.evaluate(() => {state.missions[0].title='Edited mission';render();undoCargoAction();});
    await check(() => !!findLoadById('a').load.placement && state.missions[0].title==='Edited mission' && !canUndoCargoAction(), 'unrelated mission edit invalidates history safely');
    await page.evaluate(() => {
      state.missions[0].title='Camera cargo';
      state.missions[0].loads.forEach(load=>{load.placement=null;load.rotated=false;load.loadedAt='';load.loadedByFleetEntryId='';});
      state.selectedLoadId='a';state.selectionCleared=false;cargoUndoHistory.length=0;render();
    });
    const initialFrame = await frameSize();
    const initialSpan = await page.evaluate(() => isoView.dataset.cameraSpan);
    await check(() => !document.getElementById('loadTopdownBody') && document.getElementById('shipGrid').closest('[hidden]'), 'separate loading raster replaced by top view');
    await check(() => isoView.querySelectorAll('.iso-floor.placeable').length > 0, 'existing placement targets available');
    // Click the actual rendered target instead of calling the placement handler.
    await page.evaluate(() => isoView.querySelector('.iso-floor.placeable').dispatchEvent(new MouseEvent('click', { bubbles:true })));
    await check(() => !!findLoadById('a').load.placement, 'floor click places cargo');
    await page.evaluate(() => { state.selectedLoadId='b'; render(); });
    await check(() => !!isoView.querySelector('.iso-stack-cell'), 'stack target rendered');
    await page.evaluate(() => isoView.querySelector('.iso-stack-cell').dispatchEvent(new MouseEvent('click', {bubbles:true})));
    await check(() => findLoadById('b').load.placement.z === 1, 'stack click uses existing height rules');
    const focusFixture = await page.evaluate(() => structuredClone(state));
    await page.evaluate(() => {
      findLoadById('b').load.dropoff='Area18';
      findLoadById('c').load.dropoff='Area18';
      state.selectedLoadId='c';handleCellClick(5,1);
      state.selectedLoadId=null;state.selectionCleared=true;
      state.selectedStopDropoff='Lorville';render();
    });
    await page.locator('#cargoStopFocusButton').click();
    await check(() => !!isoView.querySelector('[data-load-id="a"].is-stop-blocked') && !!isoView.querySelector('[data-load-id="b"].is-stop-blocker'), 'stop focus identifies target and external stack blocker');
    await check(() => getComputedStyle(isoView.querySelector('[data-load-id="c"]')).opacity === '0.25', 'unrelated cargo is dimmed');
    await check(() => document.getElementById('cargoStopFocusStatus').textContent.includes('Lorville') && document.querySelector('.cargo-stop-blocker').textContent.endsWith('1'), 'stop status names destination and blocker count');
    await page.locator('#loadIsoBody').screenshot({path:'.build/container-view-check/stop-focus.png'});
    await page.evaluate(() => {state.levelFilter=0;render();});
    await check(() => getComputedStyle(isoView.querySelector('[data-load-id="b"].is-stop-blocker')).opacity === '0.15', 'level filter retains transparent blocker context');
    await page.evaluate(() => {state.levelFilter='all';state.selectedStopDropoff='Area18';render();});
    await check(() => !!isoView.querySelector('[data-load-id="b"].is-stop-target') && !isoView.querySelector('.is-stop-blocker'), 'focus follows changed stop');
    await page.evaluate(() => {state.selectedStopDropoff='';render();});
    await check(() => document.querySelector('#cargoStopFocusStatus strong').textContent === buildFlightRouteState().currentDropoff, 'focus falls back to current planned stop');
    await page.locator('#cargoStopFocusButton').click();
    await check(() => !isoView.querySelector('.is-stop-background, .is-stop-blocker, .is-stop-blocked') && document.getElementById('cargoStopFocusStatus').hidden, 'toggle restores normal cargo display');
    await page.evaluate(snapshot => {state=snapshot;render();}, focusFixture);
    for (const direction of ['front','rear','left','right','top','reset']) {
      await page.click(`[data-cargo-camera="${direction}"]`);
      await page.waitForFunction(() => !cargoCameraFrame);
      await check(() => !isoView.getAttribute('viewBox').includes('NaN') && !!isoView.querySelector('.iso-face'), `${direction}: finite view with visible cargo`);
      const visibleTypes = {front:'back',rear:'front',left:'left',right:'right',top:'top',reset:'right'};
      await check(type => !!isoView.querySelector(`.iso-face-${type}`), `${direction}: correct facing surface`, visibleTypes[direction]);
      await page.evaluate(() => {state.selectedLoadId='c';render();});
      await page.locator('#isoView [data-load-id="b"] .iso-face').first().click();
      await check(() => state.selectedLoadId === 'b', `${direction}: visible container click selects cargo`);
      if (direction !== 'reset') {
        await check(view => getCargoCameraView() === view && (view === 'top' ? cargoCamera.elevation === Math.PI/2 : cargoCamera.elevation === 0), `${direction}: straight orthographic view`, direction);
        await check(view => [...isoView.querySelectorAll('.iso-face')].every(face => face.classList.contains(`iso-face-${view}`)), `${direction}: no oblique faces`, visibleTypes[direction]);
      }
      assert.deepEqual(await frameSize(), initialFrame, `${direction}: frame size unchanged`);
      assert.equal(await page.evaluate(() => isoView.dataset.cameraSpan), initialSpan, `${direction}: scale unchanged`);
    }
    await page.click('[data-cargo-camera="top"]');
    await page.waitForFunction(() => !cargoCameraFrame);
    await page.click('#isoLevelFilter [data-level-filter="0"]');
    await check(() => !!isoView.querySelector('[data-load-id="a"]:not(.is-context-level)') && !!isoView.querySelector('[data-load-id="b"].is-context-level'), 'bottom level exposes lower container and keeps upper container as context');
    await check(() => getComputedStyle(isoView.querySelector('[data-load-id="b"]')).opacity === '0.15' && getComputedStyle(isoView.querySelector('[data-load-id="b"]')).pointerEvents === 'none', 'other levels use 15 percent opacity and do not intercept clicks');
    await page.evaluate(() => {state.selectedLoadId=null;state.selectionCleared=true;render();});
    await page.locator('#isoView [data-load-id="a"] .iso-face').first().click();
    await check(() => state.selectedLoadId === 'a', 'lower container selectable through level filter');
    await page.click('#isoLevelFilter [data-level-filter="1"]');
    await check(() => !!isoView.querySelector('[data-load-id="a"].is-context-level') && !!isoView.querySelector('[data-load-id="b"]:not(.is-context-level)'), 'upper level emphasizes upper container and retains lower context');
    assert.deepEqual(await frameSize(), initialFrame, 'level filter preserves frame');
    assert.equal(await page.evaluate(() => isoView.dataset.cameraSpan), initialSpan, 'level filter preserves scale');
    await page.click('#isoLevelFilter [data-level-filter="all"]');
    await check(() => [...isoView.querySelectorAll('.iso-axis-label')].some(node => node.textContent === 'Bug') && !document.querySelector('.panel-overview-ship'), 'bow naming consistent in view and overview');
    await page.evaluate(() => { state.selectedLoadId='a'; render(); });
    await page.locator('#isoView [data-load-id="b"] .iso-face').first().click({modifiers:['Control']});
    await check(() => state.selectedLoadId === 'a', 'Ctrl click on a container never selects it');
    const tinyBox = await page.locator('#isoView [data-load-id="b"] .iso-face').first().boundingBox();
    await page.mouse.move(tinyBox.x+tinyBox.width/2,tinyBox.y+tinyBox.height/2);
    await page.keyboard.down('Control');
    await page.mouse.down();
    await page.mouse.move(tinyBox.x+tinyBox.width/2+1,tinyBox.y+tinyBox.height/2+1);
    await page.keyboard.up('Control');
    await page.mouse.up();
    await check(() => state.selectedLoadId === 'a', 'tiny Ctrl drag with modifier released first never selects cargo');
    await page.locator('#isoView [data-load-id="b"] .iso-face').first().click();
    await check(() => state.selectedLoadId === 'b', 'normal click works after suppressed camera gesture');
    await page.evaluate(() => { state.selectedLoadId='b'; render(); });
    await page.click('#cargoCameraUnload');
    await check(() => !findLoadById('b').load.placement && !!findLoadById('a').load.placement, 'unload selected top container');
    await page.click('[data-cargo-camera="reset"]');
    await page.waitForFunction(() => !cargoCameraFrame);
    await page.evaluate(() => { state.selectedLoadId='a'; render(); });
    const before = await page.evaluate(() => JSON.stringify(state.missions));
    await page.locator('#isoView').evaluate(node => node.scrollIntoView({block:'center'}));
    const box = await page.locator('#isoView').boundingBox();
    await page.mouse.move(box.x+8, box.y+8);
    await page.mouse.down();
    await page.mouse.move(box.x+45, box.y+20, {steps:5});
    await page.mouse.up();
    await check(() => cargoCamera.yaw === Math.PI/4 && cargoCamera.elevation === Math.PI/6, 'ordinary drag does not rotate');
    await page.mouse.move(box.x+box.width/2, box.y+box.height/2);
    await page.keyboard.down('Control');
    await page.mouse.down();
    await page.mouse.move(box.x+box.width/2+95, box.y+box.height/2+30, {steps:10});
    await page.mouse.up();
    await page.keyboard.up('Control');
    await page.waitForFunction(() => !cargoCameraFrame);
    assert.equal(await page.evaluate(() => JSON.stringify(state.missions)), before, 'drag must never change cargo');
    await check(() => state.selectedLoadId === 'a', 'drag does not select cargo');
    await check(() => cargoCamera.yaw !== Math.PI/4, 'Ctrl drag rotates continuously');
    assert.deepEqual(await frameSize(), initialFrame, 'free rotation preserves frame');
    assert.equal(await page.evaluate(() => isoView.dataset.cameraSpan), initialSpan, 'free rotation preserves scale');
    await page.locator('#isoView').focus();
    await page.keyboard.press('Home');
    await page.waitForFunction(() => !cargoCameraFrame);
    await check(() => cargoCamera.yaw === Math.PI/4 && isoZoomLevel === ISO_ZOOM_LEVELS[0], 'keyboard reset restores camera and zoom');
    await page.keyboard.press('ArrowLeft');
    await page.waitForFunction(() => !cargoCameraFrame);
    await check(() => cargoCamera.yaw < Math.PI/4, 'keyboard rotation');
    await page.mouse.move(box.x+box.width/2, box.y+box.height/2);
    await page.mouse.wheel(0,-100);
    await page.waitForTimeout(100);
    await check(() => isoZoomLevel === ISO_ZOOM_LEVELS[0], 'ordinary wheel does not zoom');
    await page.locator('#isoView').scrollIntoViewIfNeeded();
    const wheelBox = await page.locator('#isoView').boundingBox();
    await page.mouse.move(wheelBox.x+wheelBox.width/2,wheelBox.y+wheelBox.height/2);
    await page.keyboard.down('Control');
    await page.mouse.wheel(0,-100);
    await page.keyboard.up('Control');
    await page.waitForTimeout(100);
    await check(() => isoZoomLevel > ISO_ZOOM_LEVELS[0], 'Ctrl wheel zooms');
    assert.deepEqual(await frameSize(), initialFrame, 'zoom preserves frame dimensions');
    await page.evaluate(() => focusLoadInCargoGrid('a'));
    await page.waitForFunction(() => !cargoCameraFrame);
    await check(() => getCargoCameraView() === 'top' && !document.getElementById('loadIsoBody').hidden && state.levelFilter === 0 && state.selectedLoadId === 'a' && isoZoomLevel === 1, 'blocker guidance opens the unified top view and correct level');
    await page.evaluate(() => { uiLanguageSelect.value='en'; uiLanguageSelect.dispatchEvent(new Event('change')); });
    await check(() => document.querySelector('[data-cargo-camera="front"]').getAttribute('aria-label') === 'Bow' && document.getElementById('cargoCameraUnload').dataset.tooltip === 'Unload selected cargo', 'English icon labels and tooltips');
    await page.setViewportSize({width:390,height:844});
    await check(() => document.documentElement.scrollWidth <= innerWidth+1, 'phone layout fits viewport');
    await page.evaluate(() => {
      const yaw = cargoCamera.yaw;
      isoView.dispatchEvent(new PointerEvent('pointerdown',{pointerId:81,isPrimary:true,pointerType:'touch',clientX:10,clientY:10,button:0,bubbles:true}));
      isoView.dispatchEvent(new PointerEvent('pointercancel',{pointerId:81,bubbles:true}));
      if (cargoCamera.yaw !== yaw) throw new Error('cancelled tap changed camera');
    });
    await page.setViewportSize({width:1280,height:900});
    await page.locator('#isoView').scrollIntoViewIfNeeded();
    const touchBox = await page.locator('#isoView').boundingBox();
    const touchYaw = await page.evaluate(() => cargoCamera.yaw);
    const cdp = await page.context().newCDPSession(page);
    const touch = (x,y) => [{x,y,id:1}];
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:touch(touchBox.x+100,touchBox.y+80)});
    await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:touch(touchBox.x+160,touchBox.y+105)});
    await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
    await page.waitForFunction(() => !cargoCameraFrame);
    assert.equal(await page.evaluate(() => cargoCamera.yaw),touchYaw,'touch scrolling does not rotate');
    console.log('PASS touch scrolling does not rotate');
    await page.setViewportSize({width:1280,height:1300});
    await page.evaluate(() => {
      state.levelFilter='all';
      uiLanguageSelect.value='de';uiLanguageSelect.dispatchEvent(new Event('change'));
      render();
    });
    await page.click('[data-cargo-camera="reset"]');
    await page.waitForFunction(() => !cargoCameraFrame);
    fs.mkdirSync(path.resolve('.build/container-view-check'), {recursive:true});
    await page.locator('#loadIsoBody').evaluate(node => node.scrollIntoView({block:'center'}));
    await page.locator('#loadIsoBody').screenshot({path:'.build/container-view-check/camera.png'});
    for (const view of ['front','top']) {
      await page.click(`[data-cargo-camera="${view}"]`);
      await page.waitForFunction(() => !cargoCameraFrame);
      await page.locator('#loadIsoBody').screenshot({path:`.build/container-view-check/camera-${view}.png`});
    }
    // A Hermes-shaped fixture with a distant overload extension and extra
    // headroom above an official cell covers both kinds of overload space.
    await page.evaluate(() => {
      const original = findShipLibraryEntryById('ship:hermes');
      state.shipLibrary = state.shipLibrary.filter(ship => ship.id !== 'camera-overload');
      state.shipLibrary.push(createShipLibraryEntry({...original,id:'camera-overload',gridRows:24,
        overloadGridHeights:{X1:2,X2:2,A1:1}}));
      state.fleet[0].shipId='camera-overload';
      state.missions[0].loads.forEach(load => {load.placement=null;});
      state.autoload.allowOverload=false;
      state.levelFilter='all';state.selectedLoadId='a';state.selectionCleared=false;
      applyLayoutDefinition(getShipGridDefinition(findShipLibraryEntryById('camera-overload')),'camera-ship','camera-overload');
      render();setCargoCamera('top');
    });
    await page.waitForFunction(() => !cargoCameraFrame);
    const compactSpan = await page.evaluate(() => isoView.dataset.cameraSpan);
    await check(() => state.layout.rows === 24 && getCargoViewGeometry().bounds.maxRow === 18 && !isoView.querySelector('.iso-floor.is-overload'), 'unused overload tail does not extend frame or stern');
    const overloadToggle = page.locator('[data-page="load"] [data-autoload-overload]');
    await overloadToggle.check();
    await check(() => state.layout.overloadMode && !!isoView.querySelector('.iso-floor.is-overload[data-row="23"][data-col="0"]'), 'checkbox immediately displays distant overload cells');
    assert(Number(await page.evaluate(() => isoView.dataset.cameraSpan)) > Number(compactSpan), 'overload activation expands view bounds');
    await page.locator('#isoView .iso-floor[data-row="23"][data-col="0"]').click();
    await check(() => findLoadById('a').load.placement?.row === 23, 'manual click loads an overload cell');
    await overloadToggle.uncheck();
    await check(() => !isoView.querySelector('.iso-floor.is-overload') && !!isoView.querySelector('[data-load-id="a"]') && findLoadById('a').load.placement?.row === 23, 'disabling hides unused overload space but preserves placed cargo');
    await check(() => !resolvePlacementTarget(findLoadById('b').load,23,0,'b').valid, 'disabled overload rejects further manual placements');
    await page.evaluate(async () => {persist();await flushSoloState();});
    await page.reload();
    await page.waitForFunction(() => window.soloStartup?.phase === 'ready' && soloSync.status.hydrated && !soloSync.status.busy);
    await page.evaluate(() => {setActivePage('load');state.selectedLoadId='a';render();setCargoCamera('top');});
    await page.waitForFunction(() => !cargoCameraFrame);
    await check(() => !getAutoloadSettings().allowOverload && findLoadById('a').load.placement?.row === 23, 'reload preserves placed overload cargo even with permission off');
    await page.click('#cargoCameraUnload');
    await check(() => !findLoadById('a').load.placement && getCargoViewGeometry().bounds.maxRow === 18, 'unloading retained cargo returns to compact official bounds');
    assert.equal(await page.evaluate(() => isoView.dataset.cameraSpan), compactSpan, 'official framing restored exactly');
    await page.evaluate(() => {
      for (const id of ['a','b']) {state.selectedLoadId=id;handleCellClick(0,0);}
      state.selectedLoadId='c';render();
    });
    await check(() => !resolvePlacementTarget(findLoadById('c').load,0,0,'c').valid, 'disabled overload enforces official headroom on shared cells');
    await overloadToggle.check();
    await check(() => resolvePlacementTarget(findLoadById('c').load,0,0,'c').valid, 'enabled overload permits extra headroom');
    await page.locator('#isoView [data-load-id="b"] .iso-stack-cell').click();
    await check(() => findLoadById('c').load.placement?.z === 2, 'manual stacking uses overload headroom');
    await page.click('#isoLevelFilter [data-level-filter="0"]');
    await check(() => !!isoView.querySelector('[data-load-id="a"]:not(.is-context-level)') && !!isoView.querySelector('[data-load-id="c"].is-context-level'), 'overload and layer context work together');
    await page.locator('#loadIsoBody').evaluate(node => node.scrollIntoView({block:'center'}));
    await page.locator('#loadIsoBody').screenshot({path:'.build/container-view-check/camera-overload-context.png'});
    await page.evaluate(() => {
      const load=findLoadById('c').load;
      load.placement=null;load.width=2;load.depth=1;load.height=1;load.scu=2;load.rotated=false;
      state.levelFilter='all';state.selectedLoadId='c';state.selectionCleared=false;
      handleCellClick(5,1);state.selectedLoadId='c';state.selectionCleared=false;render();setCargoCamera('top');
    });
    await page.waitForFunction(() => !cargoCameraFrame);
    const cargoFace = () => page.locator('#isoView [data-load-id="c"] .iso-face').first();
    await cargoFace().click();
    await check(() => state.selectedLoadId === null && state.selectionCleared && !!findLoadById('c').load.placement, 'second click deselects without unloading');
    await cargoFace().click({button:'right'});
    await check(() => state.selectedLoadId === 'c' && [...document.querySelectorAll('.cargo-context-menu [role="menuitem"]')].map(n=>n.textContent).join(',') === 'Entladen,Drehen,Abwählen,Fixieren', 'right click selects cargo and opens cargo actions');
    await page.locator('[data-cargo-action="deselect"]').click();
    await check(() => !cargoContextMenu && !state.selectedLoadId && state.selectionCleared && !!findLoadById('c').load.placement, 'context deselect preserves cargo');
    await cargoFace().click({button:'right'});
    await page.keyboard.press('Escape');
    await check(() => !cargoContextMenu && document.activeElement === isoView && state.selectedLoadId === 'c', 'Escape closes menu and restores grid focus');
    await page.keyboard.press('Shift+F10');
    await page.keyboard.press('ArrowDown');
    await page.keyboard.press('Enter');
    await check(() => !cargoContextMenu && findLoadById('c').load.placement && getLoadDimensions(findLoadById('c').load,placementRotation(findLoadById('c').load)).width === 1 && getLoadDimensions(findLoadById('c').load).depth === 2, 'keyboard context action rotates a rectangular placed container');
    await cargoFace().click({button:'right'});
    await page.locator('.panel-load-iso h2').click();
    await check(() => !cargoContextMenu && !!findLoadById('c').load.placement, 'outside click closes without unloading');
    await page.waitForTimeout(250);
    await cargoFace().evaluate(node => node.dispatchEvent(new MouseEvent('contextmenu',{clientX:1279,clientY:1299,bubbles:true,cancelable:true})));
    await check(() => {const box=cargoContextMenu.getBoundingClientRect();return box.right<=innerWidth && box.bottom<=innerHeight && box.left>=0 && box.top>=0;}, 'context menu stays inside viewport edges');
    await page.locator('.cargo-context-menu').screenshot({path:'.build/container-view-check/cargo-menu.png'});
    await page.locator('[data-cargo-action="unload"]').click();
    await check(() => !findLoadById('c').load.placement && !cargoContextMenu, 'context unload removes the target container');
    await page.evaluate(() => {state.selectedLoadId='c';handleCellClick(5,1);state.selectedLoadId='c';render();});
    await page.locator('#cargoFixButton').click();
    await check(() => findLoadById('c').load.cargoFixed && !resolvePlacementTarget(findLoadById('c').load,6,1,'c').valid && !!isoView.querySelector('[data-load-id="c"] .cargo-fixed-marker'), 'fixed cargo cannot move and has a visible lock');
    await cargoFace().click({button:'right'});
    await check(() => document.querySelector('[data-cargo-action="rotate"]').disabled && document.querySelector('[data-cargo-action="unload"]').disabled, 'fixed context menu disables rotation and single unload');
    await page.locator('[data-cargo-action="fix"]').click();
    await check(() => !findLoadById('c').load.cargoFixed, 'context menu unlocks cargo');
    await page.locator('#cargoUndoButton').click();
    await check(() => findLoadById('c').load.cargoFixed, 'undo restores lock');
    const fixedPlacement=await page.evaluate(() => structuredClone(findLoadById('c').load.placement));
    await page.evaluate(() => autoLoadMission(state.missions[0]));
    await check(expected => JSON.stringify(findLoadById('c').load.placement)===JSON.stringify(expected), 'autoload preserves fixed placement', fixedPlacement);
    await check(() => sanitizeState(structuredClone(state)).missions[0].loads.find(load=>load.id==='c').cargoFixed, 'state normalization preserves fixed cargo');
    await page.evaluate(() => {
      const mission=state.missions[0];
      const b=mission.loads.find(load=>load.id==='b');
      mission.loads=mission.loads.filter(load=>load.id!=='b');
      state.missions.push({...structuredClone(mission),id:'other-contract',title:'Other contract',loads:[b]});
      state.fleet.push({id:'other-ship',shipId:'ship:hermes',manufacturer:'RSI',model:'Hermes',status:'stored'});
      state.missions.push({...structuredClone(mission),id:'external-contract',assignedFleetEntryId:'other-ship',loads:[{...structuredClone(b),id:'external-load',placement:{...b.placement,fleetEntryId:'other-ship'},loadedByFleetEntryId:'other-ship'}]});
      render();
    });
    await check(() => {
      const original=showAppNotice;let notice='';showAppNotice=async text=>{notice=text;};
      try {unloadCargoBatch('camera-mission');} finally {showAppNotice=original;}
      return !!notice && !!findLoadById('a').load.placement && !!findLoadById('c').load.placement;
    }, 'contract unload is atomic when another contract blocks it');
    await page.locator('#cargoUnloadAllButton').click();
    await check(() => !getPlacedLoadEntries().length && !!findLoadById('external-load').load.placement && !findLoadById('c').load.cargoFixed, 'unload entire ship includes fixed cargo and preserves other ships');
    await page.locator('#cargoUndoButton').click();
    await check(() => getPlacedLoadEntries().length===3 && findLoadById('c').load.cargoFixed, 'one undo restores whole ship and locks');
    await page.evaluate(() => unloadCargoBatch('other-contract'));
    await page.locator('.cargo-order-details summary').click();
    await page.locator('.mission-unload-button:not(:disabled)').first().click();
    await check(() => !getPlacedLoadEntries().length && !!findLoadById('external-load').load.placement && !isMissionCompleted(state.missions[0]), 'contract button unloads cargo without completing contract');
    assert.deepEqual(errors, [], 'no JavaScript errors');
    console.log('PASS no JavaScript errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
